scalafiddle:
  dependency: org.typelevel %%% cats-core % 1.0.1,io.circe %%% circe-core % 0.8.0,io.circe %%% circe-generic % 0.8.0,io.circe %%% circe-parser % 0.8.0
  scalaFiddleUrl: http://localhost:4000/fp-oops/
